version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes: 
    - db:/var/lib/postgresql/data

  next-app:
    container_name: next-app
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app/
    restart: always
    expose:
      - '3000'
    ports:
      - 3000:3000
    depends_on:
      - postgres

volumes:
  db:
    driver: local

