import { GetStaticProps } from 'next'
import Head from 'next/head'

import { Box, Paper } from '@mui/material'
import { Message } from '@/types'

import Layout from '@/components/Layout'
import MessageList from '@/components/MessageList'
import MessageInput from '@/components/MessageInput'

export const getStaticProps: GetStaticProps = async () => {
  const messages = [
    {
      id: '1',
      content: 'Hello world do you exist?',
      user: {
        name: 'Chris ',
        email: 'chendrix1123@gmail.com',
      },
    },
    {
      id: '2',
      content: '[Prisma](https://github.com/prisma/prisma) and Next.js go _great_ together!',
      user: {
        name: 'Nikolas Burk',
        email: 'burk@prisma.io',
      },
    }
  ]
  return {
    props: { messages },
    revalidate: 10
  }
}

type Props = {
  messages: Message[]
}

const Home: React.FC<Props> = ({ messages }) => (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main>
      <Layout>
        <Box display="flex" width="100%" justifyContent="center">
          <Paper sx={{ display: 'flex', height: '100%', width: '80%', flexDirection: 'column', p: 2 }}>
            <MessageList messages={messages} />
            <Box display="flex" flexGrow={1} justifyContent="flex-end" />
            <MessageInput />
          </Paper>
        </Box>
      </Layout>
      </main>
    </>
)

export default Home
