import Head from 'next/head'
import Image from 'next/image'
import { Box } from '@mui/material'

import Layout from '@/components/Layout'

const Home: React.FC = () => (
  <>
    <Head>
      <title>Next.js Boilerplate</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Layout>
      <Box display="flex" height="89vh" width="100%" justifyContent="center" component="main">
        <Image
          src="/next.svg"
          alt="Next.js Logo"
          width={450}
          height={92}
          priority
        />
      </Box>
    </Layout>
  </>
)

export default Home
