import { useRouter } from 'next/router'
import Head from 'next/head'
import Image from 'next/image'
import { Box } from '@mui/material'

import Layout, { PAGES } from '@/layouts/Layout'

const HomePage: React.FC = () => {
  const { route } = useRouter()
  const currentPage = PAGES.find((page) => page.route === route)

  return (
    <>
      <Head>
        <title>{`Next.js Boilerplate${currentPage ? ` - ${currentPage.name}` : ''}`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Box display="flex" width="100%" justifyContent="center" component="main">
          <Image
            src="/next.svg"
            alt="Next.js Logo"
            width={450}
            height={92}
            priority
          />
        </Box>
      </Layout>
    </>
  )
}

export default HomePage
