name: Pipeline

on:
  push:
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container: node:latest
    env:
      # next-auth
      SECRET: CI_SECRET
      GOOGLE_CLIENT_ID: blank
      GOOGLE_CLIENT_SECRET: blank
      # database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PORT: 5432
      # app
      PROTOCOL: http
      HOSTNAME: localhost
      PORT: 3000

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Expand env variables
        run: |
          echo "DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOSTNAME:$POSTGRES_PORT/$POSTGRES_DB?schema=public" >> $GITHUB_ENV
          echo "NEXTAUTH_URL=$PROTOCOL://$HOSTNAME:$PORT" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Migrate prisma schema
        run: npm run migrate
      - name: Run jest tests
        run: npm run test

  tag:
    needs: [unit-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Bump main branch version
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'}}
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: minor
          RELEASE_BRANCHES: main
          INITIAL_VERSION: '2023.0.0'

